/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
	"/website/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["WebsiteController_createWebsite"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/event": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["EventController_createEvent"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/session": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["SessionController_upsertSession"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
};
export type webhooks = Record<string, never>;
export type components = {
	schemas: {
		CreateWebsiteDto: {
			name: string;
			url: string;
			owner: string;
		};
		CreateEventDto: {
			apiKey: string;
			sessionId: string;
			/** @enum {string} */
			type: CreateEventDtoType;
			data: {
				[key: string]: unknown;
			};
		};
		UpsertSessionDto: {
			apiKey: string;
			id: string;
			referrer?: string;
			userAgent?: string;
			enteredAt?: unknown;
			exitedAt?: unknown;
			duration?: number;
			path?: string[];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
	WebsiteController_createWebsite: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateWebsiteDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	EventController_createEvent: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateEventDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	SessionController_upsertSession: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpsertSessionDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
export enum CreateEventDtoType {
	CLICK = "CLICK",
	CLICK_LINK = "CLICK_LINK",
	VIEW = "VIEW",
	SCROLL = "SCROLL",
}
